'use strict';
const KEY='PCR_LAB_LOCAL_V02';
const stageTitle={A:'独立构思 / Independent ideation',B:'AI 辅助 V1 / AI-supported V1',C:'独立批评 / Independent critique',D:'AI 辅助 V2 / AI-supported V2',E:'修改对照 / Critique-to-revision mapping',F:'事后解释 / Post-task explanation'};
let session;
try{session=JSON.parse(localStorage.getItem(KEY)||'null');if(!session||session.schema!=='pcr-participant-v1')session=PCR.start();}catch(_){session=PCR.start();}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(session));}catch(e){message('草稿本地保存失败；请尽快导出数据 / Local draft autosave failed; export your records: '+e.message,true);}}
function message(t,err=false){const m=document.getElementById('msg');m.textContent=t;m.className='status'+(err?' error':'');}
function dom(tag,parent,cls,text){const a=document.createElement(tag);if(cls)a.className=cls;if(text!==undefined)a.textContent=text;if(parent)parent.append(a);return a;}
function field(parent,key,label,opts={}){const outer=dom('div',parent,'fld');const l=dom('label',outer,'',label+(opts.required?' *':''));const e=dom(opts.short?'input':'textarea',outer);if(opts.short)e.type='text';e.name=key;e.id='f_'+key;l.htmlFor=e.id;if(opts.placeholder)e.placeholder=opts.placeholder;if(opts.rows)e.rows=opts.rows;if(opts.help)dom('div',outer,'help',opts.help);return e;}
function select(parent,key,label,choices){const x=dom('div',parent,'fld');const l=dom('label',x,'',label+' *');const e=dom('select',x);e.name=key;e.id='f_'+key;l.htmlFor=e.id;for(const [v,txt] of [['','请选择 / Select'],...choices]){const opt=dom('option',e,'',txt);opt.value=v;}return e;}
function check(parent,key,label){const wrap=dom('label',parent,'check');const e=dom('input',wrap);e.name=key;e.type='checkbox';dom('span',wrap,'',label);return e;}
function intro(root){dom('span',root,'pill','工具演示版 / Engineering demonstration · 未招募参与者 / No recruitment');dom('h2',root,'使用前说明 / Before you start');dom('p',root,'sub','本页面将原 APIC 2026 的 A–F 任务材料数字化。请勿使用真实参与者信息测试。 / This page digitises the original APIC 2026 A–F protocol. Do not enter real participant information.');dom('div',root,'warn','这是开发及流程核查原型，未获正式研究伦理审批。 / Engineering prototype only; not an approved consent or human-subject research system. Ethics, data protection, and AI-provider disclosure are required before any real study.');dom('p',root,'sub','实验任务：为 2–4 名零基础中国大学生设计涵盖 12 个马来语词汇的互动游戏；单回合 ≤15 分钟，每组材料 ≤30 元，需有主动练习与反馈。 / Design an interactive game for 2–4 Chinese university students new to Malay using 12 supplied words; ≤15 minutes per round, ≤CNY 30 materials per group, with active practice and feedback.');const t=dom('table',root,'table');for(const [i,j] of PCR.WORDS){const tr=dom('tr',t);dom('td',tr,'',i);dom('td',tr,'',j);}dom('div',root,'stat','会话编号 / Session ID: '+session.session_id);dom('div',root,'info','B、D 阶段由本地服务器调用 AI 并记录对话；原研究使用 DeepSeek 网页端，因此这是流程改编。先执行 npm start。 / In B and D, the local server calls AI and records the conversation. The source study used the DeepSeek website; this is an adapted prototype. Run npm start first.');const b=dom('button',root,'btn main','开始 A 阶段 / Start phase A');b.onclick=()=>{PCR.event(session,'stage_entered','A');persist();render();};}
function designFields(root){field(root,'materials','1. 所需材料与准备方法（含数量和成本） / Materials and setup (quantities and cost)',{required:true,rows:3});field(root,'rules','2. 主要规则与流程（≤15 分钟、覆盖 12 词） / Rules and flow (≤15 min; all 12 words)',{required:true,rows:3});field(root,'learning','3. 词汇练习及反馈方式 / Vocabulary practice and feedback',{required:true,rows:3});field(root,'ending','4. 得分、获胜或结束方式 / Scoring, winning or ending',{required:true,rows:2});field(root,'rationale','5. 设计理由 / Rationale',{required:true,rows:2});}
function viewPrevious(root,phase,title){
 const data=session.completed[phase];if(!data)return;
 const wrap=dom('details',root,'review-previous');dom('summary',wrap,'',title);
 const o=dom('pre',wrap,'previous-text');o.textContent=['materials','rules','learning','ending','rationale'].map((k,i)=>`${i+1}. ${k}: ${data[k]||''}`).join('\n\n');
}
function forms(root,p){
if(p==='A'){
 dom('div',root,'warn','A 阶段不使用 AI。独立记录构想后再进入 B。 / No AI in A. Record your own initial idea before proceeding to B.');
 field(root,'idea','1. 核心构想 / Initial game idea',{required:true});field(root,'mechanism','2. 游戏机制 / Game mechanics',{required:true});field(root,'vocabulary','3. 怎样练习或回忆 12 个词 / How players practise or recall all 12 words',{required:true});field(root,'priority','4. 最重要的设计标准 / Your main design criterion',{required:true});check(root,'confirm','我确认这些内容是在使用 AI 前由本人独立填写的。 / I confirm I wrote this independently before using AI.');
}else if(p==='B'){
 dom('div',root,'info','本版使用网页内 AI 对话及服务端自动记录，已禁用思考模式；与原研究的 DeepSeek 网页端条件不同。 / Embedded AI chat and server-side message logging are used with thinking disabled; this is not identical to the original DeepSeek website condition.');chatBox(root,p);field(root,'model','实际调用模型 / Model used',{required:true,short:true});designFields(root);field(root,'transcript','自动记录的 B 阶段 AI 对话 / Auto-captured phase-B transcript',{required:true,rows:7});field(root,'word_count','V1 字数（按 Word 手动统计） / V1 word/character count (manually checked in Word)',{required:true,short:true});check(root,'settings_confirmed','我理解使用的是预设 API 模型且会话从 B 开始。 / I understand the model is preconfigured and this AI conversation starts in B.');check(root,'word_count_confirmed','我已按原研究规则核对 V1（600–800 字）。 / I have checked V1 against the source-study 600–800 Chinese-character requirement.');check(root,'confirm','我确认 V1 由本人整理、对话自动记录。 / I confirm I compiled V1 and the system recorded the AI dialogue.');
}else if(p==='C'){
 viewPrevious(root,'B','查看已锁定的 V1 / Review locked V1 for independent critique');dom('div',root,'warn','C 阶段不与 AI 进行新的互动。阅读已锁定的 V1，独立提出问题、理由与修改建议。 / No new AI interaction in C. Review locked V1 and independently record each problem, reason, and proposal.');
 for(let n=1;n<=3;n++){dom('h3',root,'','修改建议 / Critique '+n+(n===1?'（必填：词汇学习或反馈） / Required: vocabulary practice or feedback':n===2?'（必填：玩法、可行性或规则） / Required: mechanics, feasibility or rules':'（选填） / Optional'));field(root,`crit${n}_problem`,'① V1 的具体问题 / Specific problem in V1',{required:n!==3});field(root,`crit${n}_reason`,'② 为什么这是问题 / Task-related reason',{required:n!==3});field(root,`crit${n}_proposal`,'③ 初步处理办法 / Initial proposed response',{required:n!==3});}check(root,'confirm','我确认 C 阶段没有使用生成式 AI 或他人帮助。 / I confirm no generative AI or other person assisted me in C.');
}else if(p==='D'){
 const critiques=dom('details',root,'review-previous');dom('summary',critiques,'','查看 C 阶段修改建议 / Review locked phase-C critiques');dom('pre',critiques,'previous-text',JSON.stringify(session.completed.C||{},null,2));dom('div',root,'info','继续 B 阶段的 AI 会话，依据 C 的批评进行修订。 / Continue the same AI conversation from B and use the critiques from C for revision.');chatBox(root,p);designFields(root);field(root,'transcript','自动记录的 D 阶段 AI 对话 / Auto-captured phase-D transcript',{required:true,rows:7});field(root,'word_count','V2 字数（按 Word 手动统计） / V2 word/character count (manually checked in Word)',{required:true,short:true});check(root,'same_conversation','V1 与 V2 使用同一 AI 会话。 / V1 and V2 use the same AI conversation.');check(root,'word_count_confirmed','我已按原研究规则核对 V2（600–800 字）。 / I have checked V2 against the source-study 600–800 Chinese-character requirement.');check(root,'confirm','我确认 V2 与对话记录如实。 / I confirm V2 and its AI transcript are accurate.');
}else if(p==='E'){
 viewPrevious(root,'D','查看已锁定 V2 / Review locked V2');dom('div',root,'warn','E 阶段不使用 AI。说明每项批评在 V2 中的处理情况或未采用理由。 / No AI in E. Map each critique to its treatment in V2 or explain non-adoption.');
 for(let n=1;n<=3;n++){if(n===3&&!session.completed.C.crit3_problem?.trim())continue;dom('h3',root,'','修改建议 / Critique '+n);dom('p',root,'sub',session.completed.C[`crit${n}_problem`]||'');select(root,`crit${n}_handling`,'处理方式 / Handling decision',[['as_proposed','按原想法落实 / Implemented as proposed'],['alternative','换一种方式落实 / Addressed differently'],['reasoned_nonadoption','有理由未采用 / Not adopted with reason'],['unaddressed','没有处理 / Not addressed'],['unclear','说不清 / Unclear']]);field(root,`crit${n}_evidence`,'V2 变化或未采用理由 / V2 change or reason for non-adoption',{required:n<3});}if(session.completed.C.crit3_problem?.trim()){const hidden=dom('input',root);hidden.type='hidden';hidden.name='optional_third';hidden.value='true';}check(root,'confirm','我确认 E 阶段由本人独立完成且未使用 AI。 / I confirm I completed E independently without AI.');
}else if(p==='F'){
 dom('div',root,'warn','F 阶段不使用 AI。回答属于自我报告，须与过程记录交叉核验。 / No AI in F. These are self-reports and should be cross-checked against process records.');field(root,'main_change','1. V1 到 V2 的主要变化及原因 / Main change from V1 to V2 and why',{required:true});field(root,'source','2. 变化来源：本人、AI 或共同形成？依据？ / Was the change human-led, AI-suggested or co-formed? Evidence?',{required:true});field(root,'rejected','3. 是否拒绝 AI 建议，为什么（可写“没有”） / Were any AI suggestions rejected, and why? (“None” if applicable)',{required:true});check(root,'confirm','我确认 F 阶段独立完成且未使用 AI。 / I confirm I completed F independently without AI.');}
}
function chatBox(root,p){
  const shell=dom('section',root,'chat-shell');
  dom('h3',shell,'','AI 对话工作区 / AI chat workspace · '+p+' 阶段');
  const banner=dom('div',shell,'chat-banner','正在连接本地服务器… / Connecting to local server…');banner.id='ai_status';
  const log=dom('div',shell,'chat-thread');log.id='ai_thread';
  const entry=dom('textarea',shell,'chat-entry');entry.id='ai_prompt';entry.placeholder='在此输入问题或修改要求；消息会自动记录 / Enter your request or revision prompt; all messages are logged';entry.rows=3;entry.maxLength=8000;
  const send=dom('button',shell,'btn main','发送给 AI / Send to AI');send.id='ai_send';send.type='button';
  dom('p',shell,'tiny','请勿输入身份信息。系统记录 AI 请求、回复与时间戳，但无法监测外部窗口。 / Do not enter identifying information. AI messages and timestamps are logged; external-window use cannot be observed.');
}
async function wireChat(root,stage,saveDraft){
  const status=root.querySelector('#ai_status'),thread=root.querySelector('#ai_thread'),entry=root.querySelector('#ai_prompt'),button=root.querySelector('#ai_send');
  const d=session.drafts[stage]||(session.drafts[stage]={});
  const setField=(key,value)=>{const el=root.querySelector('[name="'+key+'"]');if(el){el.value=value;d[key]=value;}saveDraft();};
  const line=(stage,role,content)=>{const wrap=dom('div',thread,'chat-message '+role);dom('div',wrap,'chat-meta',stage+' · '+(role==='user'?'参与者 / Participant':'AI'));dom('div',wrap,'chat-text',content);};
  const view=(turns)=>{thread.replaceChildren();turns.forEach(t=>line(t.stage,t.role,t.content));thread.scrollTop=thread.scrollHeight;};
  let ready=false,provider='';
  try{
    const cfgResp=await fetch('/api/status',{cache:'no-store'});if(!cfgResp.ok)throw Error('本地服务不可用 / Local server unavailable');const cfg=await cfgResp.json();provider=cfg.provider;
    const startResp=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:session.session_id})});if(!startResp.ok)throw Error((await startResp.json()).error||'初始化失败 / Session initiation failed');
    const res=await fetch('/api/session/'+encodeURIComponent(session.session_id));if(!res.ok)throw Error('无法载入对话记录 / Cannot load transcript');const current=await res.json();
    view(current.turns||[]);setField('transcript',current.transcripts?.[stage]||'');if(stage==='B')setField('model',current.model||cfg.model);
    status.textContent='已连接 / Connected · '+(cfg.live_api?'DeepSeek 实际 API / Live DeepSeek API':'合成模拟模式 / SYNTHETIC MOCK')+' · model: '+cfg.model+' · thinking: disabled';
    ready=true;
  }catch(e){status.textContent='无法连接 AI 服务 / Cannot connect to AI service: '+e.message+'。请执行 npm start 并访问 http://127.0.0.1:8787。 / Run npm start and open http://127.0.0.1:8787.';button.disabled=true;return;}
  button.onclick=async()=>{
    if(!ready||!entry.value.trim())return;
    const prompt=entry.value.trim();button.disabled=true;root.dataset.chatBusy='yes';status.textContent='等待 AI 回复… / Waiting for AI response…';
    try{
      const request_id=crypto.randomUUID();
      const resp=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:session.session_id,stage,prompt,request_id})});
      const output=await resp.json();if(!resp.ok)throw Error(output.error||'未知错误 / Unknown error');
      const all=await fetch('/api/session/'+encodeURIComponent(session.session_id));if(!all.ok)throw Error('回复已保存，但载入历史失败 / Reply saved, transcript reload failed');const latest=await all.json();view(latest.turns||[]);setField('transcript',latest.transcripts?.[stage]||'');if(stage==='B')setField('model',latest.model||output.model);
      PCR.event(session,'ai_roundtrip_complete',stage,{request_id,model:output.model,provider,server_timestamp:true});persist();entry.value='';
      status.textContent='回复已保存 / Reply saved · '+output.model+' · '+(provider==='mock'?'演示数据 / Demo data':'真实 API / Live API');
    }catch(e){status.textContent='请求未完成 / Request not confirmed: '+e.message+'（请核对服务端日志后重试） / Check server records before retrying.';}
    finally{button.disabled=false;delete root.dataset.chatBusy;}
  };
}
function snapshot(root,p){dom('h3',root,'',p+' 阶段已锁定 / Phase locked');const pre=dom('pre',root);pre.style.cssText='white-space:pre-wrap;font-size:12px;line-height:1.6;max-height:350px;overflow:auto;background:#f5f7f6;padding:14px;border-radius:8px';pre.textContent=JSON.stringify(session.completed[p],null,2);}
function finish(root){dom('span',root,'pill','全部阶段已完成 / All phases complete');dom('h2',root,'导出演示记录 / Export demo record');dom('p',root,'sub','参与者表单保存在此浏览器；导出 JSON 后可在研究者端准备匿名评审包。 / Participant form data are stored in this browser. Export JSON to prepare a blinded review packet in the researcher interface.');dom('div',root,'stat','会话编号 / Session ID: '+session.session_id);dom('div',root,'stat','过程事件数 / Recorded events: '+session.events.length);const btn=dom('button',root,'btn main','导出参与者记录 / Export participant JSON');btn.onclick=()=>save(session,session.session_id+'.json');const btn2=dom('button',root,'btn','导出事件日志 / Export event log CSV');btn2.onclick=()=>saveText(PCR.csv([['seq','type','stage','timestamp','details'],...session.events.map(x=>[x.seq,x.type,x.stage,x.at,JSON.stringify(x.details)])]),session.session_id+'_events.csv','text/csv');const reset=dom('button',root,'btn danger','清除本地演示并新建会话 / Reset local demo');reset.onclick=()=>{if(confirm('请先确认已导出数据；清除后无法恢复。继续？ / Export first. Clearing local data is irreversible. Continue?')){localStorage.removeItem(KEY);session=PCR.start();persist();render();}};dom('div',root,'warn','表单保存在当前浏览器；AI 日志位于本地服务器 runtime/。两种记录须按会话编号配对。禁止直接用于真实招募。 / Form data reside in this browser; AI logs are in the server runtime/ directory. Match by session ID. Not suitable for real recruitment.');}
function save(obj,name){saveText(JSON.stringify(obj,null,2),name,'application/json');}
function saveText(content,name,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
function render(){const root=document.getElementById('content'),nav=document.getElementById('steps');root.replaceChildren();nav.replaceChildren();message('');for(let i=0;i<6;i++){const p=PCR.PHASES[i],b=dom('div',nav,'stage '+(i<session.phase_index?'done':i===session.phase_index?'on':''));dom('div',b,'circle',i<session.phase_index?'✓':p);dom('span',b,'',stageTitle[p]);}if(session.phase_index===6){finish(root);return;}const p=PCR.PHASES[session.phase_index];dom('span',root,'pill','阶段 / Phase '+p+' / F');dom('h2',root,undefined,stageTitle[p]);dom('p',root,'sub','原 APIC 2026 流程的数字化演示。提交后界面锁定（并非防篡改记录）。 / Digital demonstration of APIC 2026. Submitted phases are UI-locked, not tamper-proof.');if(!session.events.some(x=>x.type==='stage_entered')){intro(root);return;}forms(root,p);if(p==='B'||p==='D'){for(const k of ['transcript','model']){const f=root.querySelector('[name='+k+']');if(f)f.readOnly=true;}}const fields=root.querySelectorAll('input[name],textarea[name],select[name]');const draft=session.drafts[p]||{};fields.forEach(e=>{if(e.type==='checkbox')e.checked=!!draft[e.name];else e.value=draft[e.name]||'';e.addEventListener('input',()=>{session.drafts[p]=collect();persist();});e.addEventListener('change',()=>{session.drafts[p]=collect();persist();});});function collect(){const out={};fields.forEach(e=>out[e.name]=e.type==='checkbox'?e.checked:e.value);return out;}const act=dom('div',root,'action');const btn=dom('button',act,'btn main','提交并锁定 / Submit and lock '+p+' 阶段');btn.onclick=()=>{if(root.dataset.chatBusy==='yes'){message('请等待 AI 回复完成。 / Wait for AI response before submitting.',true);return;}try{PCR.commit(session,p,collect());persist();render();}catch(err){message(err.message,true);}};const exp=dom('button',act,'btn','导出当前进度 / Export progress JSON');exp.onclick=()=>save(session,session.session_id+'_draft.json');dom('div',root,'muted','草稿自动保存至此浏览器；提交后界面锁定。 / Drafts are autosaved in this browser; submitted phases are UI-locked.');if(p==='B'||p==='D')wireChat(root,p,()=>{session.drafts[p]=collect();persist();});}
persist();render();
