'use strict';let cases=[],packetBundle=null;
const $=id=>document.getElementById(id);
function msg(x,error=false){$('msg').textContent=x;$('msg').className='status'+(error?' error':'');}
function download(obj,name){const url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function render(){const t=$('rows');t.replaceChildren();for(const s of cases){const row=document.createElement('tr');for(const v of [s.session_id,Object.keys(s.completed||{}).join(', '),PCR.complete(s)?'已完成 / Complete':'未完成 / Incomplete']){const cell=document.createElement('td');cell.textContent=v;row.append(cell);}t.append(row);}$('summary').textContent='已导入 / Imported '+cases.length+' completed records; data remain in browser memory only. / 份完成记录，当前仅存于浏览器内存。';$('pack').disabled=!cases.length;$('map').disabled=!packetBundle;}
$('files').onchange=async e=>{const files=[...e.target.files];let rejected=[];for(const f of files){try{const v=JSON.parse(await f.text());if(!PCR.complete(v)){rejected.push(f.name+'：未完成 A–F 或格式不符 / Incomplete stages or invalid format');continue;}if(cases.some(x=>x.session_id===v.session_id)){rejected.push(f.name+'：重复会话编号 / Duplicate session ID');continue;}cases.push(v);}catch(err){rejected.push(f.name+'：无效 JSON / Invalid JSON ('+err.message+'）');}}packetBundle=null;render();msg(rejected.length?rejected.join('；'):'数据导入成功 / Import succeeded.',!!rejected.length);e.target.value='';};
$('pack').onclick=()=>{try{packetBundle=PCR.buildPacket(cases);download(packetBundle.packet,'PCR_blinded_review_'+packetBundle.packet.packet_id+'.json');$('map').disabled=false;msg('已生成匿名 V2 评审包；请另外保存私有对应表。 / Blinded V2 packet exported; separately save the private ID mapping.');}catch(err){msg(err.message,true);}};
$('map').onclick=()=>{if(!packetBundle)return;download(packetBundle.private_map,'PCR_PRIVATE_MAP_'+packetBundle.packet.packet_id+'.json');msg('私有对应表已导出，请勿给评审。 / Private mapping exported; do not share with judges.');};
$('clear').onclick=()=>{cases=[];packetBundle=null;render();msg('已清空当前导入记录。 / Imported records cleared from memory.');};render();
