'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),D=require('../demo/model.js');
const nonce=()=> 'ab'.repeat(20);
function make(stage){const d=Object.fromEntries(D.REQUIRED[stage].map(k=>[k,'SYNTHETIC '+stage+' '+k]));
 if(['A','C','E','F'].includes(stage))d.independent_confirm=true;
 if(stage==='B'||stage==='D'){for(const k of D.DESIGN)d[k]='【完全虚构】'+('十'.repeat(123));}
 if(stage==='E')for(let n=1;n<=3;n++)if(d['crit'+n+'_handling'])d['crit'+n+'_handling']='implemented_as_proposed';return d;}
function login(){const s=D.fresh(),{id,code}=D.issue(s,nonce());D.activate(s,id,code);D.ack(s);D.acknowledgeTask(s);return s;}
function finish(s){for(const st of D.PHASES){if(st==='B'||st==='D')D.chat(s,'SYNTHETIC chat '+st);D.submit(s,st,make(st));}}
function ratings(){return{global_innovation:3,originality:4,educational_usefulness:5,feasibility_task_fit:2};}
test('demo codes and wrong credentials / 虚构发码',()=>{const s=D.fresh(),{id,code}=D.issue(s,nonce());assert.match(id,/^SYNTHETIC_/);assert.throws(()=>D.activate(s,id,'bad'));assert.ok(D.activate(s,id,code).activated);});
test('consent and task introduction gate are independent / 说明页与任务确认',()=>{const s=D.fresh(),{id,code}=D.issue(s,nonce());D.activate(s,id,code);assert.throws(()=>D.acknowledgeTask(s));D.ack(s);assert.deepEqual(D.inspect(D.active(s),'A',make('A')).__stage,'请完成说明和任务确认 / Complete the information and task brief');D.acknowledgeTask(s);assert.deepEqual(D.inspect(D.active(s),'A',make('A')),{});});
test('required fields and independent confirmation / 字段级必填校验',()=>{const s=login();const a=make('A');delete a.mechanism;delete a.independent_confirm;const x=D.inspect(D.active(s),'A',a);assert.ok(x.mechanism&&x.independent_confirm);assert.throws(()=>D.submit(s,'A',a));D.submit(s,'A',make('A'));assert.throws(()=>D.submit(s,'A',make('A')));});
test('character counter counts Han, Latin tokens, omits punctuation and chat / 实际字数统计',()=>{assert.equal(D.countText('你好hello world 23，！'),5);assert.equal(D.countText('A/B/C'),3);const x=make('B');assert.equal(D.countDesign(x),5*(D.countText(x.materials)));assert.ok(D.countDesign(x)>=600&&D.countDesign(x)<=800);assert.equal(D.countDesign({materials:'ABC',rules:'',learning:'',ending:'',rationale:''}),1);});
test('B & D re-count content; fabricated word_count does not override / 伪造自报字数无效',()=>{const s=login();D.submit(s,'A',make('A'));D.chat(s,'B chat');const b=make('B');b.materials='short';b.word_count='700';assert.ok(D.inspect(D.active(s),'B',b).__count);assert.throws(()=>D.submit(s,'B',b));const good=make('B');D.submit(s,'B',good);assert.equal(D.active(s).completed.B.verified_character_count,D.countDesign(good));assert.equal(D.active(s).completed.B.word_count,undefined);D.submit(s,'C',make('C'));D.chat(s,'D chat');D.submit(s,'D',make('D'));assert.equal(D.active(s).completed.D.count_algorithm,'pcr-han-latin-v1');});
test('mock AI only B/D, one continuous transcript and quota / B、D 对话共用',()=>{const s=login();assert.throws(()=>D.chat(s,'wrong'));D.submit(s,'A',make('A'));assert.ok(D.inspect(D.active(s),'B',make('B')).__chat);D.chat(s,'draft');D.submit(s,'B',make('B'));assert.throws(()=>D.chat(s,'C forbidden'));D.submit(s,'C',make('C'));D.chat(s,'refine');assert.deepEqual(D.active(s).turns.map(x=>x.stage),['B','D']);assert.ok(D.active(s).turns.every(t=>t.provider==='mock'&&!t.real_api));D.active(s).used=D.active(s).maxCalls;assert.throws(()=>D.chat(s,'over quota'));});
test('C mandatory 2 critiques, optional C3 all-or-none and E3 conditional / C→E',()=>{const s=login();D.submit(s,'A',make('A'));D.chat(s,'b');D.submit(s,'B',make('B'));const c=make('C');c.crit3_problem='extra';assert.ok(D.inspect(D.active(s),'C',c).crit3_reason);c.crit3_reason='reason';c.crit3_proposal='proposal';D.submit(s,'C',c);D.chat(s,'d');D.submit(s,'D',make('D'));assert.ok(D.inspect(D.active(s),'E',make('E')).crit3_evidence);const e=make('E');e.crit3_handling='implemented_as_proposed';e.crit3_evidence='evidence';D.submit(s,'E',e);assert.equal(D.active(s).phaseIndex,5);});
test('E rejects invalid disposition and missing explanation / E 必须亲写',()=>{const s=login();for(const st of ['A','B','C','D']){if(st==='B'||st==='D')D.chat(s,st);D.submit(s,st,make(st));}const e=make('E');e.crit2_handling='fake';e.crit1_evidence='';const errors=D.inspect(D.active(s),'E',e);assert.ok(errors.crit2_handling&&errors.crit1_evidence);});
test('full workflow, blind packet includes no IDs, turns or C / 匿名隔离',()=>{const s=login();finish(s);const pkt=D.buildPacket(s);assert.equal(pkt.items.length,1);assert.deepEqual(Object.keys(pkt.items[0]),['reviewId','v2']);assert.deepEqual(Object.keys(pkt.items[0].v2),D.DESIGN);const text=JSON.stringify(pkt);assert.ok(!text.includes('SYNTHETIC_P')&&!text.includes('mock_ai_turns')&&!text.includes('crit1_problem'));});
test('judges browse first, required four ratings and optional per-design note / 评分备注选填',()=>{const s=login();finish(s);D.buildPacket(s);assert.throws(()=>D.score(s,'J01','R01',ratings()));D.markBrowsed(s,'J01');assert.throws(()=>D.score(s,'J01','R01',{...ratings(),originality:9}));const result=D.score(s,'J01','R01',ratings());assert.equal(result.rating_note,'');assert.equal(D.completeRatings(s,'J01'),true);D.markBrowsed(s,'J02');D.score(s,'J02','R01',{...ratings(),rating_note:'SYNTHETIC note'});assert.equal(s.ratings.J02.R01.rating_note,'SYNTHETIC note');assert.ok(!('J02' in s.ratings.J01));});
test('required overall written rationale, three original checks, separate exports / 总体说明与独立提交',()=>{const s=login();finish(s);D.buildPacket(s);D.markBrowsed(s,'J01');D.score(s,'J01','R01',ratings());assert.throws(()=>D.finalizeJudge(s,'J01',[true,true,true]));assert.throws(()=>D.saveOverall(s,'J01',{criteria:'a',features:'b'}));D.saveOverall(s,'J01',{criteria:'overall standard',features:'feedback and cost',uncertainty:'none'});assert.throws(()=>D.finalizeJudge(s,'J01',[true,false,true]));D.finalizeJudge(s,'J01',[true,true,true]);const result=D.judgeExport(s,'J01');assert.deepEqual(result.confirmations,[true,true,true]);assert.equal(result.overall.criteria,'overall standard');assert.ok(!('records' in result)&&!('turns' in result));assert.throws(()=>D.score(s,'J01','R01',ratings()));assert.equal(D.safeExport(s).mode,'synthetic-only');});
test('fixture mode cannot be changed to real / 不支持真人数据',()=>{const s=login();s.mode='real';assert.throws(()=>D.issue(s,nonce()));});
