'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),D=require('../demo/model.js');
const nonce=()=> 'ab'.repeat(18);
function login(){const s=D.fresh(),{id,code}=D.issue(s,nonce());assert.ok(id.startsWith('SYNTHETIC_'));D.activate(s,id,code);D.ack(s);return s;}
const make=(stage,p)=>{const x=Object.fromEntries(D.REQUIRED[stage].map(k=>[k,'SYNTHETIC: '+stage+' '+k]));if(['B','D'].includes(stage))x.word_count='650';if(stage==='E')for(let n=1;n<=3;n++)if(x['crit'+n+'_handling'])x['crit'+n+'_handling']='implemented_as_proposed';return x;};
function finish(s){for(const st of D.PHASES){if(st==='B'||st==='D')D.chat(s,'SYNTHETIC: discuss '+st);D.submit(s,st,make(st));}}
test('codes are mock-only and wrong credentials reject',()=>{const s=D.fresh();const x=D.issue(s,nonce());assert.throws(()=>D.activate(s,x.id,'wrong'));assert.ok(D.activate(s,x.id,x.code).activated);});
test('strict stage order, acknowledgement and completeness',()=>{const s=D.fresh();const x=D.issue(s,nonce());D.activate(s,x.id,x.code);assert.throws(()=>D.submit(s,'A',make('A')));D.ack(s);assert.throws(()=>D.submit(s,'B',make('B')));assert.throws(()=>D.submit(s,'A',{idea:'x'}));D.submit(s,'A',make('A'));});
test('mock AI only B/D, continued dialogue and quota',()=>{const s=login();assert.throws(()=>D.chat(s,'hello'));D.submit(s,'A',make('A'));D.chat(s,'SYNTHETIC B');D.submit(s,'B',make('B'));assert.throws(()=>D.chat(s,'forbidden'));D.submit(s,'C',make('C'));D.chat(s,'SYNTHETIC D');assert.deepEqual(D.active(s).turns.map(x=>x.stage),['B','D']);assert.ok(D.active(s).turns.every(x=>x.provider==='mock'&&!x.real_api));});
test('C optional third critique must be complete and E must answer it',()=>{const s=login();D.submit(s,'A',make('A'));D.chat(s,'SYNTHETIC');D.submit(s,'B',make('B'));const c=make('C');c.crit3_problem='SYNTHETIC incomplete';assert.throws(()=>D.submit(s,'C',c));c.crit3_reason='SYNTHETIC reason';c.crit3_proposal='SYNTHETIC proposal';D.submit(s,'C',c);D.chat(s,'SYNTHETIC');D.submit(s,'D',make('D'));assert.throws(()=>D.submit(s,'E',make('E')));const e=make('E');e.crit3_handling='implemented_as_proposed';e.crit3_evidence='SYNTHETIC evidence';D.submit(s,'E',e);});
test('V1/V2 600–800 word count and invalid disposition rejected',()=>{const s=login();D.submit(s,'A',make('A'));D.chat(s,'SYNTHETIC');const b=make('B');b.word_count='599';assert.throws(()=>D.submit(s,'B',b));D.submit(s,'B',make('B'));D.submit(s,'C',make('C'));D.chat(s,'SYNTHETIC');D.submit(s,'D',make('D'));const e=make('E');e.crit1_handling='not_a_valid_code';assert.throws(()=>D.submit(s,'E',e));});
test('full A–F -> blinded V2 -> two independent ratings -> synthetic export',()=>{const s=login();finish(s);assert.equal(D.active(s).phaseIndex,6);const p=D.buildPacket(s);assert.equal(p.items.length,1);assert.ok(p.items[0].v2.rules);assert.ok(!('id' in p.items[0])&&!('turns' in p.items[0])&&!('A' in p.items[0]));const values={global_innovation:3,originality:4,educational_usefulness:5,feasibility_task_fit:2};D.score(s,'J01','R01',values);D.score(s,'J02','R01',values);assert.equal(Object.keys(s.ratings).length,2);assert.throws(()=>D.score(s,'J01','R01',{...values,originality:9}));assert.equal(D.safeExport(s).mode,'synthetic-only');});
test('all source data are fictional / synthetic mode guard',()=>{const s=login();s.mode='real';assert.throws(()=>D.issue(s,nonce()));});
