/* PCR Research Lab v0.4 — bilingual zero-install synthetic demonstration / 完全虚构离线交互演示。 */
(function(){'use strict';
const D=globalThis.PCR_DEMO,KEY='PCR_LAB_OFFLINE_SYNTHETIC_V04';
const stageNames={A:'独立构思 / Independent pre-AI ideation',B:'第一版设计 V1 / AI-supported first design',C:'独立批评 / Independent critique',D:'最终版本 V2 / AI-supported refinement',E:'修改处理说明 / Critique dispositions',F:'事后解释 / Post-task account'};
const instructions={
 A:'在打开 AI 前，独立写下你最初的想法。不要求成熟或完整。本阶段不能使用 AI。 / Record your first ideas independently before any AI interaction.',
 B:'与模拟 AI 讨论并完成 V1。左侧五项均须填写，合计 600–800 字。右侧聊天自动保存，无需复制聊天记录。 / Discuss with mock AI, then write a complete 600–800-character V1 using all five editor fields.',
 C:'只阅读自己的 V1，独立提出至少两条批评。批评一聚焦词汇学习或反馈，批评二聚焦玩法、规则或可行性；第三条选填。不得使用 AI。 / Independently write two critiques (third optional), each with problem, reason and proposal; no AI.',
 D:'回到 B 阶段同一段模拟 AI 对话，讨论 C 中的建议，独立确定最终 V2。完整设计仍为五项，合计 600–800 字。 / Continue the same mock conversation and produce complete V2, 600–800 characters.',
 E:'停止 AI 互动。对 C 中每条批评，选择处理方式，并由你自己说明 V2 的具体变化或没有采纳的原因。 / Without AI, choose a disposition for each earlier critique and explain the visible revision or non-adoption.',
 F:'根据自己的判断回答三项结束问题。没有采用过 AI 建议可以填写“没有”。不得使用 AI。 / Independently answer all three post-task questions; “none” is valid for rejected suggestions.'
};
const fields={
 A:[['idea','1. 你想设计什么样的教育游戏？ / Initial game idea'],['mechanism','2. 玩家具体要做什么？主要游戏机制 / What players do and the mechanics'],['vocabulary','3. 如何练习或回忆 12 个词？ / Vocabulary practice and recall'],['priority','4. 最重要的设计标准是什么？ / Priority design criterion']],
 B:[['materials','1. 所需材料与准备方法（包括成本） / Materials, preparation and cost'],['rules','2. 主要规则和流程（2–4 人、≤15 分钟、覆盖全部词） / Rules and flow'],['learning','3. 词汇练习与明确反馈 / Vocabulary practice and feedback'],['ending','4. 得分、获胜或结束方式 / Scoring, winning or ending'],['rationale','5. 为什么适合零基础大学生？ / Rationale for beginner students']],
 C:[['crit1_problem','① 问题：V1 哪处影响词汇练习或反馈？ / C1 problem: vocabulary or feedback'],['crit1_reason','② 理由：为什么需要修改？ / C1 reason'],['crit1_proposal','③ 建议：准备如何处理？ / C1 proposed response'],['crit2_problem','① 问题：玩法、规则或可行性哪里不足？ / C2 problem: mechanics or feasibility'],['crit2_reason','② 理由：为什么影响任务要求？ / C2 reason'],['crit2_proposal','③ 建议：准备如何处理？ / C2 proposed response'],['crit3_problem','① 可选问题 / C3 optional problem'],['crit3_reason','② 可选理由 / C3 optional reason'],['crit3_proposal','③ 可选建议 / C3 optional proposal']],
 D:[['materials','1. 修订后的材料与准备 / Revised materials and preparation'],['rules','2. 完整 V2 规则与流程 / Complete revised rules'],['learning','3. V2 词汇练习和反馈 / Revised practice and feedback'],['ending','4. V2 得分或结束方式 / Revised ending'],['rationale','5. V2 如何满足任务要求？ / Revised rationale']],
 F:[['main_change','1. V1→V2 最重要的变化是什么？为什么？ / Main change and why'],['source','2. 变化主要来自本人、AI 还是双方共同形成？如何判断？ / Origin of change and reasoning'],['rejected','3. 有哪些 AI 建议最终未采用？为什么？没有可写“没有”。 / Rejected AI suggestions and why (or none)']]
};
const dispositions=[['','请选择 / Choose'],['implemented_as_proposed','按原想法落实 / Implemented as proposed'],['implemented_differently','换一种方式落实 / Implemented differently'],['reasoned_not_adopted','有理由未采用 / Not adopted with reason'],['unaddressed','没有处理 / Not addressed'],['unclear','说不清 / Unclear']];
const dimensions=[['global_innovation','整体创新表现 / Global innovation'],['originality','独创性 / Originality'],['educational_usefulness','教育用途 / Educational usefulness'],['feasibility_task_fit','可行性与任务适配 / Feasibility and task fit']];
let s;try{s=D.check(JSON.parse(localStorage.getItem(KEY)));}catch(_){s=D.fresh();}
let view='admin',lastIssued=null,judge='J01',judgeAt=0,judgeStep='browse';
const $=id=>document.getElementById(id);
const elem=(tag,parent,cls,txt)=>{const el=document.createElement(tag);if(cls)el.className=cls;if(txt!==undefined)el.textContent=txt;if(parent)parent.append(el);return el;};
function persist(){try{localStorage.setItem(KEY,JSON.stringify(s));}catch(e){tell('浏览器保存失败，请立即导出 / Browser save failed; export now: '+e.message,true);}}
function tell(t,bad=false){const m=$('notice');m.textContent=t;m.className='status'+(bad?' error':'');}
function run(fn){try{const result=fn();persist();render();return result;}catch(e){if(e.fields)paintErrors(e.fields);tell(e.message,true);return null;}}
function switchTo(next){view=next;render();}
function card(title,caption,parent=$('app')){const el=elem('section',parent,'card');elem('h2',el,'',title);if(caption)elem('p',el,'muted',caption);return el;}
function button(parent,label,fn,style=''){const b=elem('button',parent,style,label);b.type='button';b.addEventListener('click',fn);return b;}
function inputField(parent,key,label,value='',kind='textarea'){const w=elem('div',parent,'input-group'),l=elem('label',w,'',label);const el=elem(kind,l);el.dataset.field=key;el.id='field-'+key;if(kind==='textarea')el.rows=3;el.value=value??'';elem('div',w,'field-error').dataset.errorFor=key;return el;}
function selectField(parent,key,label,value='',options=[]){const w=elem('div',parent,'input-group'),l=elem('label',w,'',label),el=elem('select',l);el.dataset.field=key;el.id='field-'+key;for(const [v,t]of options){const o=elem('option',el,'',t);o.value=v;}el.value=value??'';elem('div',w,'field-error').dataset.errorFor=key;return el;}
function checkbox(parent,key,label,checked=false){const w=elem('label',parent,'checkline'),el=elem('input',w);el.type='checkbox';el.dataset.field=key;el.id='field-'+key;el.checked=checked;elem('span',w,'',label);elem('div',parent,'field-error').dataset.errorFor=key;return el;}
function paintErrors(errors){for(const n of document.querySelectorAll('.field-error'))n.textContent='';for(const field of document.querySelectorAll('.invalid'))field.classList.remove('invalid');let first=null;for(const [key,msg]of Object.entries(errors)){const item=document.querySelector('[data-error-for="'+key+'"]');if(item){item.textContent=msg;const el=$('field-'+key);if(el){el.classList.add('invalid');first??=el;}}else if(key==='__chat'||key==='__count'||key==='__stage'){const node=$('stage-validation');if(node)node.textContent+=(node.textContent?' · ':'')+msg;}}
if(first)first.focus();}
function download(data,name){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=elem('a',document.body);a.href=url;a.download=name;a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function nonce(){if(!globalThis.crypto?.getRandomValues)throw Error('此浏览器缺少安全随机数功能 / Browser secure randomness unavailable');const bytes=new Uint8Array(20);crypto.getRandomValues(bytes);return[...bytes].map(x=>x.toString(16).padStart(2,'0')).join('');}
function admin(){const c=card('研究者控制台 / Researcher console','只管理完全虚构的演示身份和记录。此浏览器没有真正的身份隔离。 / Synthetic case management only; no genuine authentication.');const actions=elem('div',c,'row');button(actions,'生成虚构编号及访问码 / Issue synthetic code',()=>run(()=>{lastIssued=D.issue(s,nonce());}));button(actions,'导出虚构演示记录 / Export demonstration JSON',()=>download(D.safeExport(s),'SYNTHETIC_PCR_demo_v04.json'),'secondary');button(actions,'清空全部模拟记录 / Reset demo data',()=>{if(!confirm('清除本浏览器中的全部虚构测试记录？ / Clear all synthetic records?'))return;s=D.fresh();lastIssued=null;persist();render();},'danger');
 if(lastIssued){const x=elem('div',c,'record');elem('strong',x,'','刚签发的模拟凭证 / Newly issued demonstration code');elem('div',x,'',lastIssued.id);elem('div',x,'',lastIssued.code);button(x,'以此编号进入参与者端 / Open participant view',()=>switchTo('participant'),'secondary');}
 const people=Object.values(s.people);elem('h3',c,'','实验进度 / Synthetic cases');if(!people.length)elem('p',c,'muted','尚未生成虚构编号 / No synthetic IDs issued.');else{const t=elem('table',c),thead=elem('tr',t);for(const v of ['编号 / ID','进度 / Progress','AI 轮次 / Mock turns'])elem('th',thead,'',v);for(const p of people){const row=elem('tr',t);for(const v of [p.id,p.phaseIndex===6?'完成 / Complete':D.PHASES[p.phaseIndex]+' / Working',p.used+'/'+p.maxCalls])elem('td',row,'',String(v));}}
 const cp=card('匿名评审准备 / Blinded review preparation','将完成的 V2 单独制作为匿名评审包。重新生成会清空原有模拟评分。 / Creating a packet resets previous synthetic ratings.');button(cp,'生成匿名 V2 评分包 / Generate blinded packet',()=>run(()=>D.buildPacket(s)));if(s.packet){elem('p',cp,'pill','匿名方案 / Blinded designs: '+s.packet.items.length);const r=elem('div',cp,'row');button(r,'下载匿名 V2 JSON / Export blind packet',()=>download(s.packet,'SYNTHETIC_Blinded_V2_packet.json'),'secondary');button(r,'前往评审端 / Open judge view',()=>{judgeStep='browse';switchTo('judge');},'secondary');}}
function sample(stage,key){const samples={A:{idea:'【完全虚构】制作一款能够记忆 12 个马来语词汇的卡牌互动游戏。',mechanism:'【完全虚构】2–4 位玩家轮流抽词卡并匹配生活情境卡，其他玩家核对答案。',vocabulary:'【完全虚构】所有词汇必须至少一次被辨认、口头回忆或放入情境中使用。',priority:'【完全虚构】练习机会公平、反馈及时且材料成本可控。'},C:{crit1_problem:'【完全虚构】部分词汇只被展示，玩家缺少独立回忆机会。',crit1_reason:'【完全虚构】只看到词卡不能确定玩家是否记住含义。',crit1_proposal:'【完全虚构】加入遮挡答案后的口头回忆，并立即反馈。',crit2_problem:'【完全虚构】目前规则没有保证 15 分钟内覆盖全部词语。',crit2_reason:'【完全虚构】抽卡随机，可能重复出现熟悉的词而漏掉其他词。',crit2_proposal:'【完全虚构】按固定的十二张词卡轮转，每轮设定时间。'},F:{main_change:'【完全虚构】加入答题后的快速核对环节，从只看词卡改成主动回忆，因为这能提供明确的错误反馈。',source:'【完全虚构】最初的问题由参与者自己发现，之后参考模拟 AI 提示完善操作步骤；这是主观来源判断。',rejected:'【完全虚构】没有使用模拟 AI 提出的复杂积分方案，因为它会增加计时负担。'}};if(samples[stage]?.[key])return samples[stage][key];
 if(stage==='B'||stage==='D'){const base='【完全虚构的游戏设计】两至四名零基础大学生使用十二张马来语词汇卡和对应的中文提示卡参加一轮不超过十五分钟的互动活动。每个人轮流选择词卡，说出含义并给出生活情境例子。同伴即时核对答案，答错后使用提示再尝试一次。每张卡都应被使用，材料可重复打印，总成本控制在三十元以内。';let out='';while(D.countText(out)<122)out+=base;return out;}
 if(stage==='E'&&key.includes('evidence'))return'【完全虚构】参与者在 V2 的规则或反馈段落中明确说明采取的修改，并指出这样做的原因。';return'';}
function login(){const c=card('虚构参与者登录 / Synthetic participant login','请输入研究者端生成的虚构编号和一次性模拟访问码。仅用于演示，不提供安全身份验证。 / Demo credentials have no security guarantees.');const id=inputField(c,'login_id','虚构编号 / Synthetic ID',lastIssued?.id||'','input'),code=inputField(c,'login_code','模拟访问码 / Mock access code',lastIssued?.code||'','input');code.type='password';button(c,'进入实验 / Activate demo session',()=>run(()=>D.activate(s,id.value.trim(),code.value.trim())));}
function information(p){const c=card('研究说明与知情确认 / Study information and consent confirmation','请先阅读以下简短说明，再自愿确认。/ Read before continuing.');
 for(const [head,content]of [
 ['目的 / Purpose','演示如何记录教育游戏的人机共创过程、V1/V2 版本和匿名作品评审。 / Demonstrates capture of game-design stages and blinded product appraisal.'],
 ['预计时间 / Time','原研究任务约一小时；此处可用虚构样例加快测试。 / Original activity ~1 hour; synthetic demo may be faster.'],
 ['会记录什么 / Records','当前浏览器会保存六阶段作答、模拟 AI 消息与时间、评分及总体说明。 / Browser storage contains staged answers, mock messages, timestamps and demo ratings.'],
 ['隐私与退出 / Privacy and exit','演示数据保存在当前浏览器，不能用于真实参与者；可以停止操作或由研究者清空。/ Browser data are not private study storage. Stop anytime or reset.'],
 ['外部服务 / Third parties','不调用 DeepSeek、Cloudflare 或外部服务器，模拟 AI 回复不会被发送至网络。 / No real AI/provider network calls.']]){const b=elem('div',c,'info-row');elem('h3',b,'',head);elem('p',b,'muted',content);}
 const box=checkbox(c,'consent','我已阅读说明，并确认仅以虚构内容测试此原型 / I have read this and will use fictional content only');button(c,'确认并继续 / Confirm and continue',()=>{if(!box.checked){paintErrors({consent:'请主动确认后继续 / Confirm explicitly'});return;}run(()=>D.ack(s));});elem('p',c,'quiet','此确认是演示交互，不构成已经获批的正式研究知情同意书。 / This is not ethics-approved human-subject consent.');}
function taskBrief(){const c=card('教育游戏共创任务介绍 / Educational game co-creation task','独立任务说明 / Task brief');elem('p',c,'','为 2–4 名此前未接触过马来语的中国大学生，设计一款练习下列 12 个日常词汇的互动游戏。 / Design a game for 2–4 Chinese university beginners learning these 12 Malay words.');
 const t=elem('div',c,'vocab-grid');for(const [malay,zh] of globalThis.PCR.WORDS){const w=elem('div',t,'vocab-pair');elem('strong',w,'',malay);elem('span',w,'',zh);}
 const ul=elem('ul',c);for(const item of ['一个回合 ≤15 分钟，覆盖 12 词 / One ≤15-minute round using all twelve words','使用常见材料，每组成本 ≤30 元 / Common materials, ≤CNY 30 per group','主动辨认、回忆或在情境中使用词语，并有明确反馈 / Active practice and explicit feedback','必须具有互动机制；不能只是词表、抄写或普通选择题 / Include interaction beyond a word list or standard quiz','V1 和 V2 均写材料、规则、练习反馈、结束方式、设计理由 / Both designs contain five components'])elem('li',ul,'',item);
 elem('p',c,'note','阶段顺序 A→F。A、C、E、F 禁止 AI；B、D 允许页面内模拟 AI，且使用同一段会话。原材料中的时间建议只供安排节奏，不作为强制倒计时。 / A/C/E/F independent; B/D mock AI in one conversation. Timing guidance is not a countdown.');const ack=checkbox(c,'brief','我已阅读任务要求 / I have read the task brief');button(c,'开始阶段 A / Start phase A',()=>{if(!ack.checked){paintErrors({brief:'请确认已阅读 / Confirm you have read the brief'});return;}run(()=>D.acknowledgeTask(s));});}
function stageSteps(p){const steps=elem('div',$('app'),'steps');D.PHASES.forEach((st,i)=>elem('span',steps,'step '+(i<p.phaseIndex?'done':i===p.phaseIndex?'active':''),st));}
function readonlyDesign(parent,stage,data){const box=elem('details',parent,'reference');box.open=true;elem('summary',box,'',stage+' 已提交设计（只读） / Submitted '+stage+' (read-only)');for(const [k,title]of fields[stage]){const b=elem('div',box,'record');elem('strong',b,'',title);elem('div',b,'',data?.[k]||'—');}return box;}
function phase(){const p=D.active(s),stage=D.PHASES[p.phaseIndex];if(!stage){finished(p);return;}stageSteps(p);
 const intro=card('阶段 '+stage+' · '+stageNames[stage],instructions[stage]);const tag=elem('p',intro,stage==='B'||stage==='D'?'pill':'note',stage==='B'||stage==='D'?'允许模拟 AI · Mock AI allowed':'不得使用 AI · Independent only');tag.setAttribute('aria-label','AI usage rule');
 if(stage==='C')readonlyDesign(intro,'B',p.completed.B);if(stage==='E')readonlyDesign(intro,'D',p.completed.D);
 const frame=elem('div',$('app'),stage==='B'||stage==='D'?'workbench':'');
 const editor=card('填写内容 / '+(stage==='B'||stage==='D'?'Design editor':'Responses'),'每项前标有说明，所有必填字段必须填写；草稿自动保存在本浏览器。 / Required fields; browser-local autosave.',frame);const form=elem('form',editor);form.id='phase-form';const draft=p.drafts[stage]||{};
 if(stage==='E')for(let n=1;n<=2+(p.completed.C?.crit3_problem?1:0);n++){const group=elem('div',form,'critique-card');elem('h3',group,'','批评 '+n+' / Critique '+n);elem('p',group,'readonly-quote',p.completed.C['crit'+n+'_problem']);selectField(group,'crit'+n+'_handling','处理方式（必填）/ Handling (required)',draft['crit'+n+'_handling']||'',dispositions);inputField(group,'crit'+n+'_evidence','请自行描述 V2 的变化、位置或未采用理由（必填） / Your own explanation',draft['crit'+n+'_evidence']||'');}
 else if(stage==='C'){for(let n=1;n<=3;n++){const group=elem('div',form,'critique-card');elem('h3',group,'',n===3?'第三条批评（选填） / Optional critique 3':n===1?'第一条批评：词汇学习或反馈 / Critique 1: vocabulary and feedback':'第二条批评：玩法或可行性 / Critique 2: mechanics and feasibility');for(const [key,label]of fields.C.filter(([key])=>key.startsWith('crit'+n+'_')))inputField(group,key,label,draft[key]||'');}}
 else for(const [key,label]of fields[stage])inputField(form,key,label,draft[key]||'');
 let countPanel=null;
 if(stage==='B'||stage==='D'){countPanel=elem('div',form,'count-panel');elem('strong',countPanel,'','设计字数 / Design length');const display=elem('span',countPanel,'count-result','尚未统计 / Not counted');display.id='length-result';button(countPanel,'统计字数 / Count characters',()=>countLength(false),'secondary');elem('p',countPanel,'quiet','汉字各计 1 字，连续英文/数字按 1 个词计；不包含 AI 对话、标题和标点。修改后需重新统计。 / Han characters = 1 each; Latin/numeric tokens = 1; chat, headings and punctuation excluded.');}
 let workCheck=null;if(['A','C','E','F'].includes(stage))workCheck=checkbox(form,'independent_confirm','我确认由本人独立完成本阶段，没有在此阶段使用 AI / I completed this phase independently without AI',draft.independent_confirm===true);
 const validation=elem('p',form,'field-error');validation.id='stage-validation';const bar=elem('div',form,'row');button(bar,'填写完全虚构示例 / Fill fictional example',()=>{for(const el of form.querySelectorAll('[data-field]')){if(el.type==='checkbox'){el.checked=true;continue;}if(stage==='C'&&el.dataset.field.startsWith('crit3_'))continue;el.value=el.tagName==='SELECT'?'implemented_as_proposed':sample(stage,el.dataset.field);}form.dispatchEvent(new Event('input',{bubbles:true}));tell('已填入虚构示例，请核对后提交 / Fictional sample ready');},'secondary');const send=elem('button',bar,'','校验并提交，进入下一阶段 / Validate and submit');send.type='submit';
 function gather(){return Object.fromEntries([...form.querySelectorAll('[data-field]')].map(el=>[el.dataset.field,el.type==='checkbox'?el.checked:el.value]));}
 function saveDraft(){p.drafts[stage]=gather();verifiedText=null;persist();}
 let verifiedText=null;
 function countLength(onSubmit){const count=D.countDesign(gather());const pass=count>=600&&count<=800;const display=$('length-result');if(display){display.textContent=count+' / 600–800 '+(pass?'✓ 符合 / Valid':count<600?'· 不足 '+(600-count)+' 字 / Too short':'· 超出 '+(count-800)+' 字 / Too long');display.className='count-result '+(pass?'ok':'bad');}if(!onSubmit)verifiedText=JSON.stringify(Object.fromEntries(D.DESIGN.map(k=>[k,gather()[k]])));return pass;}
 form.addEventListener('input',()=>{saveDraft();if(countPanel){$('length-result').textContent='已修改，请重新统计 / Changed; recount required';$('length-result').className='count-result';}const panel=$('stage-validation');if(panel)panel.textContent='';for(const x of form.querySelectorAll('.invalid'))x.classList.remove('invalid');for(const n of form.querySelectorAll('.field-error'))if(n.id!=='stage-validation')n.textContent='';});
 form.addEventListener('submit',e=>{e.preventDefault();const data=gather();if(countPanel){const actualText=JSON.stringify(Object.fromEntries(D.DESIGN.map(k=>[k,data[k]])));countLength(true);if(verifiedText!==actualText){paintErrors({__count:'请先点击统计字数并确认结果，再提交 / Click Count to verify the final edited text'});return;}}
 const errors=D.inspect(p,stage,data);if(Object.keys(errors).length){paintErrors(errors);tell('请补齐高亮项目 / Fix required fields',true);return;}run(()=>D.submit(s,stage,data));});
 if(stage==='B'||stage==='D')renderChat(frame,p,stage);
}
function renderChat(frame,p,stage){const box=card('模拟 AI 对话 / Mock AI chat','完整记录参与者输入与模拟回复，B/D 共用同一会话。 / Automatically logs all in-app turns; B and D share one thread.',frame);box.classList.add('chat-panel');const history=elem('div',box,'chat-history');history.id='chat-history';history.setAttribute('aria-label','AI dialogue history');if(!p.turns.length)elem('p',history,'muted','暂无消息，请在下方发送 / No messages yet.');for(const turn of p.turns){const b=elem('div',history,'chat-turn');elem('div',b,'chat-meta','阶段 '+turn.stage+' · '+new Date(turn.at).toLocaleTimeString()+' / '+turn.stage);elem('div',b,'bubble user-bubble',turn.prompt);elem('div',b,'bubble ai-bubble',turn.reply);}
 const compose=elem('form',box,'composer');compose.id='mock-chat-form';const msg=elem('textarea',compose);msg.id='chat-prompt';msg.rows=3;msg.placeholder='在这里向模拟 AI 发送问题 / Message the mock AI';msg.setAttribute('aria-label','Message mock AI');const send=elem('button',compose,'','发送模拟消息 / Send mock message');send.type='submit';const status=elem('p',compose,'quiet','已使用 '+p.used+'/'+p.maxCalls+' 次模拟 AI / Mock calls used');compose.addEventListener('submit',e=>{e.preventDefault();if(!msg.value.trim()){tell('消息不能为空 / Enter a message',true);msg.focus();return;}run(()=>D.chat(s,msg.value));});history.scrollTop=history.scrollHeight;}
function participant(){const p=s.active?s.people[s.active]:null;if(!p||!p.activated){login();return;}if(!p.consentAck){information(p);return;}if(!p.taskBriefAck){taskBrief();return;}if(p.phaseIndex===6){finished(p);return;}phase();}
function finished(p){const c=card('A–F 已完成 / Study workflow completed','恭喜完成这份虚构流程测试。 / The fictional A–F walkthrough is complete.');const stats=elem('div',c,'summary-grid');for(const [label,value]of [['已提交阶段 / Completed phases','6 / 6'],['V1 字数 / First design count',p.completed.B?.verified_character_count],['V2 字数 / Final design count',p.completed.D?.verified_character_count],['模拟 AI 轮次 / Mock AI turns',p.turns.length],['实际用时 / Elapsed time',p.startedAt&&p.finishedAt?Math.round((new Date(p.finishedAt)-new Date(p.startedAt))/60000)+' min':'—']]){const box=elem('div',stats,'stat');elem('span',box,'muted',label);elem('strong',box,'',String(value??'—'));}elem('p',c,'note','作品与聊天记录均为模拟内容。请先下载备份，再返回研究者端建立盲评包。 / Export the fictional data before switching to researcher review.');const row=elem('div',c,'row');button(row,'导出本案例虚构记录 / Export synthetic record',()=>download({schema:D.SCHEMA,mode:'synthetic-only',case:{id:p.id,completed:p.completed,turns:p.turns}},p.id+'_v04.json'),'secondary');button(row,'返回研究者端 / Researcher',()=>switchTo('admin'));}
function judgeOverview(){const c=card('独立匿名评审 / Independent blinded appraisal','只展示匿名 V2。原研究要求先通读全部方案，再按原四维量规独立评分。 / Read all blinded designs before independently scoring.');if(!s.packet){elem('p',c,'note','请先让研究者生成匿名评分包 / No blinded packet available.');return false;}
 const picker=selectField(c,'judge','评审编号 / Judge ID',judge,[['J01','J01'],['J02','J02']]);picker.addEventListener('change',()=>{judge=picker.value;judgeStep=D.judgeRecord(s,judge).finalizedAt?'done':D.judgeRecord(s,judge).browsedAll?'rate':'browse';judgeAt=0;render();});const progress=elem('p',c,'pill',judge+' · '+Object.keys(s.ratings[judge]||{}).length+'/'+s.packet.items.length+' 已评分 / Rated');return true;}
function judgeBrowse(){const c=card('先通读全部匿名 V2 / Browse all blinded designs','原评审流程要求先了解全部方案的表现范围。这里不会展示过程记录、AI 对话或参与者编号。 / Original procedure: inspect all products before rating.');for(const item of s.packet.items){const d=elem('details',c,'review-detail');elem('summary',d,'','匿名方案 '+item.reviewId+' / Design '+item.reviewId);for(const [key,label]of fields.D){const box=elem('div',d,'record');elem('strong',box,'',label);elem('p',box,'',item.v2[key]);}}
 const ck=checkbox(c,'browsed','我已浏览全部匿名 V2，准备独立评分 / I have reviewed all anonymised designs');button(c,'进入逐份评分 / Start rating',()=>{if(!ck.checked){paintErrors({browsed:'请先确认 / Please confirm'});return;}run(()=>{D.markBrowsed(s,judge);judgeStep='rate';});});}
function judgeRate(){const packet=s.packet,item=packet.items[judgeAt];if(!item){judgeStep='audit';render();return;}const c=card('逐份评分 / Rate each design',item.reviewId+' · '+(judgeAt+1)+' / '+packet.items.length);for(const [key,label]of fields.D){const b=elem('div',c,'record');elem('strong',b,'',label);elem('div',b,'',item.v2[key]);}const form=elem('form',c);form.id='rating-form';elem('h3',form,'','原 APIC 四维评分量规 / Original analytic rubric');elem('p',form,'muted','1、3、5 为描述锚点，2、4 为相邻中间水平。每个分数都必须填写；单份备注选填。 / Anchors at 1/3/5, 2/4 intermediate; note optional.');const past=s.ratings[judge]?.[item.reviewId]||{};for(const [key,label]of dimensions){const d=elem('details',form,'rubric');elem('summary',d,'',label+' · 查看原量规 / Show original anchors');(globalThis.PCR?.ANCHORS?.[key]||[]).forEach((text,i)=>elem('p',d,'muted',(i*2+1)+' 分 / points: '+text));const field=selectField(form,key,label,past[key]==null?'':String(past[key]),[['','请选择 / Choose'],...Array.from({length:5},(_,i)=>[String(i+1),String(i+1)])]);field.required=true;}inputField(form,'rating_note','单份作品简短评分备注（选填）/ Per-design short rating note (optional)',past.rating_note||'');const row=elem('div',form,'row');button(row,'上一份 / Previous',()=>{judgeAt=Math.max(0,judgeAt-1);render();},'secondary');const submit=elem('button',row,'','保存评分并继续 / Save and continue');submit.type='submit';button(row,'检查已评分作品 / Review scores',()=>{judgeStep='audit';render();},'secondary');form.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries([...form.querySelectorAll('[data-field]')].map(x=>[x.dataset.field,x.value]));try{D.score(s,judge,item.reviewId,data);persist();const next=packet.items.findIndex(x=>!s.ratings[judge]?.[x.reviewId]);if(next>=0){judgeAt=next;judgeStep='rate';}else judgeStep='audit';render();}catch(err){tell(err.message,true);}});}
function judgeAudit(){const c=card('全部评分核查 / Audit all ratings','四维分数全部填写后才能进入总体评分说明；可返回任一作品修改。 / Review and edit ratings before the overall rationale.');const table=elem('table',c),head=elem('tr',table);for(const t of ['编号 / ID','四维评分 / Scores','备注 / Note','修改 / Edit'])elem('th',head,'',t);for(let i=0;i<s.packet.items.length;i++){const it=s.packet.items[i],rating=s.ratings[judge]?.[it.reviewId];const tr=elem('tr',table);elem('td',tr,'',it.reviewId);elem('td',tr,'',rating?D.DIMENSIONS.map(k=>rating[k]).join(' / '):'未完成 / Missing');elem('td',tr,'',rating?.rating_note||'—');const td=elem('td',tr);button(td,'修改 / Edit',()=>{judgeAt=i;judgeStep='rate';render();},'secondary');}const next=button(c,'评分完整，填写总体说明 / Write overall rationale',()=>{judgeStep='overall';render();});if(!D.completeRatings(s,judge)){next.disabled=true;elem('p',c,'field-error','仍有未填写评分 / Some ratings are missing');}}
function judgeOverall(){const c=card('总体评分说明 / Overall rating rationale','原研究评审曾口头表达整体评价，这里将该环节规范为书面记录。不是对历史口头内容的逐字转录。 / Written summary of previously oral-style overall impressions; no invented historical transcript.');const form=elem('form',c);form.id='overall-form';const old=D.judgeRecord(s,judge).overall||{};for(const [key,label]of [['criteria','总体评分主要依据 / Main criteria behind your ratings'],['features','影响判断最大的作品特征或共同问题 / Influential design patterns and examples'],['uncertainty','难以判断的地方或不确定性（没有写“无”）/ Uncertainties (write “none” if applicable)']])inputField(form,key,label,old[key]||'');const row=elem('div',form,'row');button(row,'返回评分核查 / Back to ratings',()=>{judgeStep='audit';render();},'secondary');const submit=elem('button',row,'','保存总体说明 / Save overall rationale');submit.type='submit';form.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries([...form.querySelectorAll('[data-field]')].map(x=>[x.dataset.field,x.value]));run(()=>{D.saveOverall(s,judge,d);judgeStep='confirm';});});}
function judgeConfirm(){const c=card('最终独立评分确认 / Final independent judge confirmation','请确认原始匿名评分表中的三项要求，随后提交并锁定。 / Confirm the three original judge statements.');const checks=[checkbox(c,'confirm1','已浏览全部匿名方案并独立完成评分 / I reviewed all blinded designs and rated independently'),checkbox(c,'confirm2','没有与另一位评审讨论，也没有查看对方的评分 / I did not discuss or view the other judge’s scores'),checkbox(c,'confirm3','已核对每份作品的四维分数均为 1–5 整数 / I verified all four 1–5 scores for every design')];button(c,'确认并结束评审 / Confirm and finish',()=>{if(checks.some(x=>!x.checked)){tell('请确认全部三项 / Confirm all three statements',true);return;}run(()=>{D.finalizeJudge(s,judge,checks.map(x=>x.checked));judgeStep='done';});});}
function judgeDone(){const c=card('评审已完成 / Judge completed','模拟结果已锁定，可以导出独立的评审 JSON。 / Synthetic ratings finalized and ready to export.');const x=D.judgeRecord(s,judge);elem('p',c,'pill',judge+' · '+x.finalizedAt);button(c,'导出 '+judge+' 评分与总体说明 JSON / Export judge results',()=>{try{download(D.judgeExport(s,judge),'SYNTHETIC_'+judge+'_ratings_v04.json');}catch(e){tell(e.message,true);}});}
function judgeView(){if(!judgeOverview())return;const state=D.judgeRecord(s,judge);if(state.finalizedAt)judgeStep='done';else if(!state.browsedAll)judgeStep='browse';else if(judgeStep==='browse')judgeStep='rate';if(judgeStep==='browse')judgeBrowse();else if(judgeStep==='rate')judgeRate();else if(judgeStep==='audit')judgeAudit();else if(judgeStep==='overall')judgeOverall();else if(judgeStep==='confirm')judgeConfirm();else judgeDone();}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.id==='tab-'+view));$('app').replaceChildren();tell('');if(view==='admin')admin();else if(view==='participant')participant();else judgeView();}
$('tab-admin').addEventListener('click',()=>switchTo('admin'));$('tab-participant').addEventListener('click',()=>switchTo('participant'));$('tab-judge').addEventListener('click',()=>switchTo('judge'));render();
})();
