/* PCR offline demonstration UI — all participant data is fictional. / 全部为虚构数据。 */
(function(){'use strict';
const D=globalThis.PCR_DEMO,KEY='PCR_LAB_OFFLINE_SYNTHETIC_V1';
const stageNames={A:'独立构思 / Independent ideation',B:'AI 辅助初稿 V1 / AI-supported V1',C:'独立批评 / Independent critique',D:'AI 辅助修改 V2 / AI-supported refinement',E:'批评处理说明 / Critique dispositions',F:'事后解释 / Post-task account'};
const fields={
 A:[['idea','游戏核心构想 / Initial game idea'],['mechanism','游戏机制 / Game mechanics'],['vocabulary','如何练习 12 词 / Practising 12 words'],['priority','最重要的设计标准 / Priority criterion']],
 B:[['materials','材料及成本 / Materials and cost'],['rules','游戏规则（回合不超过 15 分钟） / Rules and flow'],['learning','词汇练习和反馈 / Vocabulary practice and feedback'],['ending','得分或结束方式 / Scoring and ending'],['rationale','设计理由 / Design rationale']],
 C:[['crit1_problem','批评 1：问题 / Critique 1: problem'],['crit1_reason','批评 1：理由 / Reason'],['crit1_proposal','批评 1：建议 / Proposed response'],['crit2_problem','批评 2：问题 / Critique 2: problem'],['crit2_reason','批评 2：理由 / Reason'],['crit2_proposal','批评 2：建议 / Proposed response'],['crit3_problem','可选批评 3：问题 / Optional critique 3: problem'],['crit3_reason','可选批评 3：理由 / Optional reason'],['crit3_proposal','可选批评 3：建议 / Optional proposal']],
 D:[['materials','修订后材料及成本 / Revised materials and cost'],['rules','修订后玩法 / Revised rules'],['learning','修订后词汇练习与反馈 / Revised vocabulary and feedback'],['ending','修订后结束方式 / Revised ending'],['rationale','修订理由 / Rationale']],
 F:[['main_change','V1→V2 最重要的变化及理由 / Main change and why'],['source','变化来自本人、AI 还是共同形成 / Source of change'],['rejected','拒绝的 AI 建议及原因（没有则写“没有”） / Rejected AI advice, if any']]
};
const dispositions=[['','请选择 / Select'],['implemented_as_proposed','按原建议落实 / Implemented as proposed'],['implemented_differently','改用其他方式 / Implemented differently'],['reasoned_not_adopted','有理由未采用 / Reasoned non-adoption'],['unaddressed','未处理 / Unaddressed'],['unclear','说不清 / Unclear']];
const dimensions=[['global_innovation','整体创新表现 / Global innovation'],['originality','独创性 / Originality'],['educational_usefulness','教育用途 / Educational usefulness'],['feasibility_task_fit','可行性与任务适配 / Feasibility and task fit']];
let s;try{s=D.check(JSON.parse(localStorage.getItem(KEY)));}catch(_){s=D.fresh();}let view='admin',lastIssued=null,judge='J01',judgeAt=0;
const $=id=>document.getElementById(id),elem=(tag,parent,cls,txt)=>{const el=document.createElement(tag);if(cls)el.className=cls;if(txt!==undefined)el.textContent=txt;if(parent)parent.append(el);return el;};
function persist(){try{localStorage.setItem(KEY,JSON.stringify(s));}catch(e){tell('无法保存浏览器演示数据 / Unable to save demo data: '+e.message,true);}}
function tell(t,isErr=false){const n=$('notice');n.textContent=t;n.className='status'+(isErr?' error':'');}
function run(fn){try{fn();persist();render();}catch(e){tell(e.message,true);}}
function switchTo(next){view=next;render();}
function card(title,caption){const c=elem('section',$('app'),'card');elem('h2',c,'',title);if(caption)elem('p',c,'muted',caption);return c;}
function button(parent,caption,fn,cls){const b=elem('button',parent,cls||'',caption);b.type='button';b.addEventListener('click',fn);return b;}
function inputField(parent,key,label,value='',kind='textarea'){const w=elem('label',parent,'',label);const el=elem(kind,w);el.dataset.field=key;if(kind==='textarea')el.rows=3;el.value=value??'';return el;}
function selectField(parent,key,label,value='',choices=[]){const w=elem('label',parent,'',label),el=elem('select',w);el.dataset.field=key;for(const [k,title] of choices){const op=elem('option',el,'',title);op.value=k;}el.value=value||'';return el;}
function download(data,name){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const a=elem('a',document.body);a.href=url;a.download=name;a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function nonce(){if(!globalThis.crypto?.getRandomValues)throw Error('该浏览器不支持安全随机码 / Secure browser randomness unavailable');const bytes=new Uint8Array(18);crypto.getRandomValues(bytes);return Array.from(bytes,x=>x.toString(16).padStart(2,'0')).join('');}
function admin(){const c=card('研究者控制台 / Researcher console','所有编号、代码和日志均为本浏览器中的虚构演示内容 / All credentials and records exist only in this browser as a demonstration.');
const row=elem('div',c,'row');button(row,'生成虚构编号及访问码 / Issue synthetic code',()=>run(()=>{lastIssued=D.issue(s,nonce());}));button(row,'导出虚构演示记录 / Export synthetic test results',()=>run(()=>download(D.safeExport(s),'SYNTHETIC_PCR_demo.json')),'secondary');button(row,'清空所有演示数据 / Reset all demo data',()=>{if(!confirm('确认清除本浏览器全部虚构演示数据？ / Delete all demo data?'))return;s=D.fresh();lastIssued=null;persist();render();},'danger');
if(lastIssued){const x=elem('div',c,'record');elem('strong',x,'','最新生成的演示凭证 / Newly issued mock credentials');elem('div',x,'',lastIssued.id);elem('div',x,'',lastIssued.code);button(x,'使用该编号继续 / Use this ID',()=>{switchTo('participant');},'secondary');}
const rows=Object.values(s.people);elem('h3',c,'','虚构参与者概览 / Synthetic participants');if(!rows.length)elem('p',c,'muted','请先生成测试编号 / Create a synthetic ID to begin.');else{const table=elem('table',c),thead=elem('tr',table);for(const label of ['编号 / ID','进度 / Progress','AI 调用 / Mock calls'])elem('th',thead,'',label);for(const p of rows){const tr=elem('tr',table);for(const v of [p.id,p.phaseIndex===6?'A–F 完成 / Complete':D.PHASES[p.phaseIndex]+' / In progress',p.used+'/'+p.maxCalls])elem('td',tr,'',String(v));}}
const pcard=card('匿名评审包 / Blinded packet','只有虚构案例完成全部六阶段，才能生成只含 V2 的匿名评分包。/ Includes only final V2 of finished synthetic cases.');button(pcard,'生成匿名 V2 评分包 / Create blinded V2 packet',()=>run(()=>{D.buildPacket(s);tell('已生成匿名评分包 / Packet created');}));if(s.packet){elem('p',pcard,'pill','匿名方案数 / Designs: '+s.packet.items.length);button(pcard,'下载匿名评分包 JSON / Download packet',()=>download(s.packet,'SYNTHETIC_Blinded_V2_packet.json'),'secondary');button(pcard,'前往评审端 / Open judge view',()=>switchTo('judge'),'secondary');}
}
function sampleValue(stage,key){if(key==='word_count')return '630';if(key.includes('handling'))return 'implemented_as_proposed';if(stage==='B'||stage==='D')return Array(3).fill('【虚构示例】设计者应解释玩家如何练习词汇、得到反馈，并检验规则能否在十五分钟内完成。').join('');const sample={A:{idea:'【虚构示例】使用词卡构建马来语学习游戏。',mechanism:'【虚构示例】玩家轮流抽卡并匹配图片。',vocabulary:'【虚构示例】12 个词均可通过记忆和反馈进行练习。',priority:'【虚构示例】兼顾互动和明确反馈。'},C:{crit1_problem:'【虚构示例】第一版反馈不清晰。',crit1_reason:'【虚构示例】可能影响词汇辨认。',crit1_proposal:'【虚构示例】提供答案卡。',crit2_problem:'【虚构示例】游戏可能超时。',crit2_reason:'【虚构示例】初学者需时间辨认词卡。',crit2_proposal:'【虚构示例】限制轮次。'},E:{crit1_evidence:'【虚构示例】V2 已添加答案卡。',crit2_evidence:'【虚构示例】V2 已减少轮次。'},F:{main_change:'【虚构示例】增加了具体反馈机制。',source:'【虚构示例】最初由参与者提出，与模拟 AI 继续讨论。',rejected:'【虚构示例】拒绝复杂计分规则，因为会超过时间。'}};return sample[stage]?.[key]||'【虚构示例】用于验证网页字段和提交机制。';}
function participant(){let p=s.active?s.people[s.active]:null;if(!p||!p.activated||p.phaseIndex===6){const c=card('模拟参与者登录 / Synthetic participant login','研究者页面中的虚构编号与临时访问码仅验证演示流程，不是安全认证。 / Demo credentials are not secure authentication.');const id=inputField(c,'login_id','虚构参与者编号 / Synthetic participant ID',lastIssued?.id||'','input');id.id='login-id';const code=inputField(c,'login_code','临时访问码 / Temporary demonstration code',lastIssued?.code||'','input');code.id='login-code';code.type='password';button(c,'登录演示 / Activate mock session',()=>run(()=>{D.activate(s,id.value.trim(),code.value.trim());}));if(p?.phaseIndex===6)elem('p',c,'note','该虚构案例已完成。可以切换研究者页面生成新编号 / This synthetic case is complete. Issue a fresh code.');return;}
const c=card('参与者实验 / Participant task',p.id+' · 已使用模拟 AI / Mock AI calls: '+p.used+'/'+p.maxCalls);
if(!p.confirmed){elem('p',c,'note','这是研究软件功能演示，不是正式知情同意页；不得录入真实参与者资料。 / This is not a real consent process; never enter personal study data.');button(c,'我确认仅使用虚构内容 / I will use synthetic content only',()=>run(()=>D.ack(s)));return;}
const steps=elem('div',c,'steps');D.PHASES.forEach((st,i)=>elem('span',steps,'step '+(i<p.phaseIndex?'done':i===p.phaseIndex?'active':''),st));const stage=D.PHASES[p.phaseIndex];
elem('h3',c,'','阶段 '+stage+' / '+stageNames[stage]);elem('p',c,'muted','实验任务：为 2–4 位零基础大学生设计 12 个马来语词汇的短时游戏；一回合不超过 15 分钟、常见材料不超过人民币 30 元，包含主动练习和反馈。 / Design a vocabulary game for 2–4 novice adults, 12 words, ≤15 minutes and ≤CNY 30, with practice and feedback.');const vocab=elem('details',c);elem('summary',vocab,'','12 个目标词与译义 / The twelve task words');elem('p',vocab,'muted',(globalThis.PCR?.WORDS||[]).map(x=>x[0]+' — '+x[1]).join(' · '));
if(stage==='B'||stage==='D'){const box=elem('div',c,'card');elem('h3',box,'','模拟 AI 对话 / Mock model conversation');elem('p',box,'muted','B、D 使用同一虚构对话上下文；本按钮不调用 DeepSeek。 / B and D share the same simulated transcript. No DeepSeek call.');for(const turn of p.turns){const v=elem('div',box,'record');elem('strong',v,'',turn.stage+' · 提示 / Prompt');elem('div',v,'',turn.prompt);elem('strong',v,'','模拟回复 / Mock response');elem('div',v,'',turn.reply);}const msg=inputField(box,'chat_prompt','向模拟 AI 发送消息 / Send a mock prompt');msg.id='chat-prompt';button(box,'发送模拟消息 / Send mock message',()=>run(()=>{D.chat(s,msg.value);}), 'secondary');}
const form=elem('form',c);form.id='phase-form';const draft=p.drafts[stage]||{};
if(stage==='E'){for(let i=1;i<=2+(p.completed.C?.crit3_problem?1:0);i++){elem('h3',form,'','批评 '+i+' / Critique '+i);elem('p',form,'muted',p.completed.C['crit'+i+'_problem']);selectField(form,'crit'+i+'_handling','处理方式 / Disposition',draft['crit'+i+'_handling'],dispositions);inputField(form,'crit'+i+'_evidence','V2 位置或理由 / V2 evidence or reason',draft['crit'+i+'_evidence']);}}
else for(const [key,label] of fields[stage])inputField(form,key,label,draft[key]);
if(stage==='B'||stage==='D'){const count=inputField(form,'word_count','V1 / V2 字数（自行核对 600–800） / Declared character count (600–800)',draft.word_count||'','input');count.type='number';count.min='600';count.max='800';}
const buttons=elem('div',form,'row');button(buttons,'填入完整虚构示例 / Fill fictional sample',()=>{for(const el of form.querySelectorAll('[data-field]')){const key=el.dataset.field;if(key.startsWith('crit3_')&&stage==='C')continue;el.value=sampleValue(stage,key);}form.dispatchEvent(new Event('input',{bubbles:true}));tell('已填充虚构内容，可修改后提交 / Synthetic sample filled');},'secondary');const submit=elem('button',buttons,'','提交并进入下一阶段 / Submit and continue');submit.type='submit';
function gather(){return Object.fromEntries([...form.querySelectorAll('[data-field]')].map(el=>[el.dataset.field,el.value]));}
form.addEventListener('input',()=>{p.drafts[stage]=gather();persist();});form.addEventListener('submit',e=>{e.preventDefault();run(()=>D.submit(s,stage,gather()));});
}
function judgeView(){const c=card('独立匿名评审 / Blinded product appraisal','评审只看到匿名 V2 及评分量规，不访问 A–C、AI 轨迹或身份映射。 / Only blinded V2 and four-dimensional rubric are shown.');if(!s.packet){elem('p',c,'note','请先在研究者端生成匿名评分包 / Ask researcher to generate the blinded packet.');return;}
const picker=selectField(c,'judge','评审编号 / Judge ID',judge,[['J01','J01'],['J02','J02']]);picker.id='judge-id';picker.addEventListener('change',()=>{judge=picker.value;judgeAt=0;render();});const packet=s.packet;const item=packet.items[judgeAt];if(!item){elem('p',c,'muted','评分已完成 / All items covered');return;}elem('p',c,'pill',item.reviewId+' ('+(judgeAt+1)+'/'+packet.items.length+')');
const product=elem('section',c,'');for(const [key,label] of fields.D){const block=elem('div',product,'record');elem('strong',block,'',label);elem('div',block,'',item.v2[key]);}
const form=elem('form',c);form.id='rating-form';elem('h3',form,'','四维评分（1–5） / Four-dimensional rating');elem('p',form,'muted','请依据下方原 APIC 的 1/3/5 分描述锚点独立评分；2 和 4 为相邻水平。 / Use the original APIC anchors below. Scores 2 and 4 represent intermediate levels.');for(const [key,label]of dimensions){const d=elem('details',form);elem('summary',d,'',label+' — 原量规 / Original anchors');const anchors=globalThis.PCR?.ANCHORS?.[key]||[];anchors.forEach((anchor,i)=>elem('p',d,'muted',(i*2+1)+' 分 / points: '+anchor));const input=selectField(form,key,label,(s.ratings[judge]||{})[item.reviewId]?.[key]?.toString()||'',[['','请选择 / Choose'],...Array.from({length:5},(_,i)=>[String(i+1),String(i+1)])]);input.required=true;}
const row=elem('div',form,'row');button(row,'上一份 / Previous',()=>{judgeAt=Math.max(0,judgeAt-1);render();},'secondary');const submit=elem('button',row,'','保存评分并继续 / Save rating and continue');submit.type='submit';button(row,'下一份 / Next',()=>{judgeAt=Math.min(packet.items.length-1,judgeAt+1);render();},'secondary');form.addEventListener('submit',e=>{e.preventDefault();run(()=>{const vals=Object.fromEntries([...form.querySelectorAll('[data-field]')].map(el=>[el.dataset.field,el.value]));D.score(s,judge,item.reviewId,vals);judgeAt=Math.min(packet.items.length-1,judgeAt+1);});});
const x=elem('div',c,'row');button(x,'导出当前评审的虚构评分 / Export this judge\u2019s synthetic ratings',()=>download({schema:'pcr-synthetic-judge-scores-v1',judge,ratings:s.ratings[judge]||{}},'SYNTHETIC_'+judge+'_ratings.json'),'secondary');}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.id==='tab-'+view));$('app').replaceChildren();tell('');if(view==='admin')admin();else if(view==='participant')participant();else judgeView();}
$('tab-admin').addEventListener('click',()=>switchTo('admin'));$('tab-participant').addEventListener('click',()=>switchTo('participant'));$('tab-judge').addEventListener('click',()=>switchTo('judge'));render();
})();
