/* PCR Research Lab — Offline Synthetic Demo / 完全虚构的离线流程演示 */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PCR_DEMO=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const SCHEMA='pcr-offline-synthetic-demo-v1', PHASES=['A','B','C','D','E','F'];
const REQUIRED={A:['idea','mechanism','vocabulary','priority'],B:['materials','rules','learning','ending','rationale'],C:['crit1_problem','crit1_reason','crit1_proposal','crit2_problem','crit2_reason','crit2_proposal'],D:['materials','rules','learning','ending','rationale'],E:['crit1_handling','crit1_evidence','crit2_handling','crit2_evidence'],F:['main_change','source','rejected']};
const has=x=>typeof x==='string'&&!!x.trim();
const copy=x=>JSON.parse(JSON.stringify(x));
function fresh(){return{schema:SCHEMA,mode:'synthetic-only',next:1,people:{},active:null,packet:null,ratings:{},events:[]};}
function check(s){if(!s||s.schema!==SCHEMA||s.mode!=='synthetic-only'||!s.people)throw Error('仅支持虚构演示 / Synthetic demonstration only');return s;}
function issue(s,nonce){check(s);const id='SYNTHETIC_P'+String(s.next++).padStart(3,'0');const code='DEMO-'+String(nonce||'').replace(/[^a-zA-Z0-9]/g,'').slice(0,30);if(code.length<20)throw Error('需要足够长的模拟随机码 / A random demo code is required');s.people[id]={id,code,activated:false,confirmed:false,phaseIndex:0,completed:{},drafts:{},turns:[],used:0,maxCalls:10,createdAt:new Date().toISOString()};s.events.push({type:'issued',id});return{id,code};}
function activate(s,id,code){check(s);const p=s.people[id];if(!p||!has(code)||p.code!==code)throw Error('模拟编号或访问码错误 / Invalid demo credentials');if(p.phaseIndex===6)throw Error('已完成的模拟案例不能重新登录 / Completed session');p.activated=true;s.active=id;return p;}
function active(s){check(s);const p=s.people[s.active];if(!p||!p.activated)throw Error('请先激活模拟编号 / Activate a demo participant');return p;}
function ack(s){const p=active(s);p.confirmed=true;return p;}
function validate(p,stage,answers){if(PHASES[p.phaseIndex]!==stage)throw Error('请依次完成 A–F / Strict A–F sequence');if(!p.confirmed)throw Error('请先确认虚构测试 / Confirm synthetic-only demonstration');if(!answers||typeof answers!=='object')throw Error('Missing submission');const missing=REQUIRED[stage].filter(k=>!has(answers[k]));if(missing.length)throw Error('未填写必填项 / Missing: '+missing.join(', '));
if(stage==='C'){const opt=['crit3_problem','crit3_reason','crit3_proposal'];if(opt.some(k=>has(answers[k]))&&!opt.every(k=>has(answers[k])))throw Error('第三条批评应完整填写 / Complete optional critique');}
if(stage==='E'){const choices=['implemented_as_proposed','implemented_differently','reasoned_not_adopted','unaddressed','unclear'];for(let i=1;i<=3;i++){if(i===3&&!has(p.completed.C?.crit3_problem))continue;if(!choices.includes(answers['crit'+i+'_handling'])||!has(answers['crit'+i+'_evidence']))throw Error('必须逐条说明批评如何处理 / Missing critique disposition '+i);}}
if(stage==='B'||stage==='D'){if(!p.turns.some(t=>t.stage===stage))throw Error('本阶段需要至少一次模拟 AI 对话 / At least one mock AI turn required');const n=Number(answers.word_count);if(!Number.isInteger(n)||n<600||n>800)throw Error('原研究 V1/V2 要求 600–800 字 / Original study: 600–800 characters');}
return true;}
function submit(s,stage,answers){const p=active(s);validate(p,stage,answers);p.completed[stage]=copy(answers);delete p.drafts[stage];p.phaseIndex++;s.events.push({type:'stage_submitted',id:p.id,stage,at:new Date().toISOString()});return p;}
function chat(s,message){const p=active(s);const stage=PHASES[p.phaseIndex];if(!p.confirmed||!['B','D'].includes(stage))throw Error('模拟 AI 仅允许 B、D / AI only in B/D');if(!has(message))throw Error('请输入提示 / Enter a prompt');if(p.used>=p.maxCalls)throw Error('模拟调用额度已用完 / Mock quota exhausted');const turn={stage,prompt:message.trim(),reply:'【模拟回复 / MOCK】建议明确学习目标、游戏流程与即时反馈，并由你自行判断哪些建议适合当前任务。 / Clarify learning objectives, rules and feedback; evaluate every suggestion independently.',at:new Date().toISOString(),provider:'mock',real_api:false};p.turns.push(turn);p.used++;s.events.push({type:'mock_ai_turn',id:p.id,stage});return turn;}
function buildPacket(s){check(s);const done=Object.values(s.people).filter(p=>p.phaseIndex===6);if(!done.length)throw Error('暂无已完成案例 / No completed case');s.packet={schema:'pcr-synthetic-blinded-v1',mode:'synthetic-only',task:'SYNTHETIC 12 Malay-word educational game / 虚构的马来语词汇游戏设计',items:done.map((p,i)=>({reviewId:'R'+String(i+1).padStart(2,'0'),v2:copy(p.completed.D)}))};return s.packet;}
function score(s,judge,rid,values){check(s);if(!['J01','J02'].includes(judge))throw Error('仅支持 J01 或 J02');if(!s.packet?.items.some(x=>x.reviewId===rid))throw Error('Unknown review ID');const keys=['global_innovation','originality','educational_usefulness','feasibility_task_fit'];for(const k of keys)if(!Number.isInteger(Number(values[k]))||Number(values[k])<1||Number(values[k])>5)throw Error('四个维度都要填 1–5 整数 / Four integer scores required');s.ratings[judge]??={};s.ratings[judge][rid]=Object.fromEntries(keys.map(k=>[k,Number(values[k])]));return s.ratings[judge][rid];}
function safeExport(s){check(s);return{schema:SCHEMA,mode:'synthetic-only',records:Object.values(s.people).map(p=>({id:p.id,completed:copy(p.completed),mock_ai_turns:copy(p.turns),used:p.used})),packet:copy(s.packet),ratings:copy(s.ratings),events:copy(s.events)};}
return{SCHEMA,PHASES,REQUIRED,fresh,check,issue,activate,active,ack,validate,submit,chat,buildPacket,score,safeExport};
});
